server:
  port: 8081

spring:
  data:
    mongodb:
      database: PersonsDB
      #uri: mongodb://localhost:27017
      uri: mongodb+srv://uday:NQNPQm9axheij5Kb@cluster0-g9hbi.mongodb.net/PersonsDB?authSource=admin
      key:
        vault:
          database: "encryption"
          collection: "__keyVault"
          name: "demo-data-key"
      kmsprovider: "local"
      encryption:
        #cryptdpath: "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongocryptd"
        masterKeyPath: "master-key.txt"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
logging:
  level:
    org.springframework: ERROR
    com.paychex: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
